version: '3'

services: 
  postgresql:
    image: postgres:12
    container_name: postgresql
    volumes: 
      - postgres_vol:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports: 
      - "5432:5432"
    networks: 
      - postgres_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: .env
    volumes:
      - pgadmin_vol:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - postgres_network
    restart: always

volumes: 
  postgres_vol:
  pgadmin_vol:

networks: 
  postgres_network: